global class MBFieldDefinition {
    @AuraEnabled
    @InvocableVariable
    public String EntityDefinitionId;
    @AuraEnabled
    @InvocableVariable
    public String DeveloperName;
    @AuraEnabled
    @InvocableVariable
    public String Description;
    @AuraEnabled
    @InvocableVariable
    public String ComplianceGroup;
    @AuraEnabled
    @InvocableVariable
    public String SecurityClassification;
}
