global class MBSecurityHealthCheckRisks {
    @AuraEnabled
    @InvocableVariable
    public String RiskType;
    @AuraEnabled
    @InvocableVariable
    public String Setting;
    @AuraEnabled
    @InvocableVariable
    public String SettingGroup;
    @AuraEnabled
    @InvocableVariable
    public String OrgValue;
    @AuraEnabled
    @InvocableVariable
    public String SettingRiskCategory;
    @AuraEnabled
    @InvocableVariable
    public String StandardValue;
}
